
version: "3.9"

services:
  backend:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
